#!/usr/bin/with-contenv bash

### Set Defaults
AUTH_TYPE=${AUTH_TYPE:-"MYSQL"}
POSTMASTER=${POSTMASTER:-"postmaster@example.org"}
HOSTNAME=${HOSTNAME:-"mail.example.org"}
LOG_LEVEL=${LOG_LEVEL:-"INFO"}
LOG_PATH=${LOG_PATH:-"/var/log/dovecot/dovecot.log"}
LOG_DEBUG_PATH=${LOG_DEBUG_PATH:-"/var/log/dovecot/dovecot.debug.log"}
LOG_INFO_PATH=${LOG_INFO_PATH:-"/dev/stdout"}
GREETING_TEXT=${GREETING_TEXT:-"Ready"}
SSL_CRT_FILENAME=${SSL_CRT_FILENAME:-"mail.crt"}
SSL_KEY_FILENAME=${SSL_KEY_FILENAME:-"mail.key"}
PASS_SCHEME=${PASS_SCHEME:-"MD5-CRYPT"}


### Config Helper
	function setDovecotConf {
		KEY="$1"
		VALUE="$2"
		FILE="$3"
		echo "Setting conf: $KEY=$VALUE in ($FILE)"
		sed -i -e "s#^\s*.$KEY\s*=.*\$#$KEY=$VALUE#g" $FILE
	}


#### Create Vmail Dir
	if [ ! -d "/var/mail" ]; then
		mkdir -p /var/mail
	fi
	chown -R vmail:mail /var/mail

#### Set Permissions
    chown -R vmail:vmail /etc/dovecot/sieve
    chmox +x /etc/dovecot/sieve/bin/*

#### Set Hostname
	setDovecotConf "hostname" "$HOSTNAME" /etc/dovecot/dovecot.conf
	setDovecotConf "postmaster_address" "$POSTMASTER" /etc/dovecot/dovecot.conf

#### Set Greeting
    setDovecotConf "login_greeting" "$GREETING_TEXT" /etc/dovecot/dovecot.conf
	
#### Set Loglevel Dovecot Loglevel
	setDovecotConf "log_path" "$LOG_PATH" /etc/dovecot/dovecot.conf
	setDovecotConf "debug_log_path" "$LOG_DEBUG_PATH" /etc/dovecot/dovecot.conf
	setDovecotConf "info_log_path" "$LOG_INFO_PATH" /etc/dovecot/dovecot.conf

#### Auth Type Setup
    case "$AUTH_TYPE" in
      "MYSQL" | "mysql")
			DB_PORT=${DB_PORT:-"3306"}
		##### Check MySQL Connectivity			
		    while true; do
		      mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
		      out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
		      echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
		      if [ $? -eq 0 ]; then
		        echo "** [dovecot] MySQL Database Connection Established"
		        break
		      fi
		      echo "** [dovecot] MySQL Database Connection Not avilable, retrying.."
		      sleep 2
		    done

		##### Update Dovecot SQL Configuration
			cat <<EOF > /etc/dovecot/dovecot-sql.conf
driver = mysql
connect = host=$DB_HOST port=$DB_PORT dbname=$DB_NAME user=$DB_USER password=$DB_PASS
default_pass_scheme = $PASS_SCHEME
password_query = SELECT username AS user, password, homedir AS userdb_home, 999 AS userdb_uid, 8 AS userdb_gid FROM mailbox WHERE username = '%u' 
iterate_query = SELECT username AS user FROM mailbox
user_query = SELECT homedir AS home, maildir AS mail, concat('*:bytes=', quota) as quota_rule, 999 AS uid, 8 AS gid FROM mailbox WHERE username = '%u'
EOF

			sed -i -e "/connect = /c\connect = host=$DB_HOST port=$DB_PORT dbname=$DB_NAME user=$DB_USER password=$DB_PASS" /etc/dovecot/pigeonhole-sieve.dict


		##### Check to see if Table Exists
		    if [ $(mysql -N -s -u $DB_USER -p$DB_PASS -h $DB_HOST -e "select count(*) from information_schema.tables where table_schema='${DB_NAME}' and table_name='mailbox';") -eq 1 ]; then
		        echo "** [dovecot] MySQL Config Database Tables exist"
		    else
		    echo "** [dovecot] No MySQL Config Database Tables exist! Creating.."
		    mysql -u$DB_USER -h$DB_HOST -p$DB_PASS $DB_NAME</assets/dovecot/sql/schema.sql
		    echo '** [dovecot] Database Configured to '$DB_HOST'/'$DB_NAME
		fi	      

		sed -i -e 's/##changeme##/sql/g' /etc/dovecot/dovecot.conf
	    ;;
    esac

### SSL Configuration
	if [ ! -f /assets/certs/$SSL_CRT_FILENAME ] || [ ! -f /assets/certs/$SSL_KEY_FILENAME ]; then
	    echo "** [dovecot] SSL Key or certificate not found. Generating self-signed certificates"
		mkdir -p /assets/certs
	    openssl genrsa -out /assets/certs/$SSL_KEY_FILENAME
	    openssl req -new -key /assets/certs/$SSL_KEY_FILENAME -out /assets/certs/${SSL_CRT_FILENAME%.*}.csr -subj "/CN=dovecot"
	    openssl x509 -req -days 3650 -in /assets/certs/${SSL_CRT_FILENAME%.*}.csr -signkey /assets/certs/$SSL_KEY_FILENAME -out /assets/certs/$SSL_CRT_FILENAME
	fi

	setDovecotConf "ssl_cert" "</assets/certs/$SSL_CRT_FILENAME" /etc/dovecot/dovecot.conf
	setDovecotConf "ssl_key" "</assets/certs/$SSL_KEY_FILENAME" /etc/dovecot/dovecot.conf

    if [ ! -f "/assets/certs/server.pem" ] || [ ! -f "/assets/certs/server.key" ]; then	        
	 	    cat <<EOF > /tmp/openssl.cnf
[ req ]
default_bits = 1024
encrypt_key = yes
distinguished_name = req_dn
x509_extensions = cert_type
prompt = no

[ req_dn ]
# country (2 letter code)
C=XX

# State or Province Name (full name)
ST=XX

# Locality Name (eg. city)
L=Test Server

# Organization (eg. company)
O=Dovecot

# Organizational Unit Name (eg. section)
OU=IMAP server

# Common Name (*.example.com is also possible)
CN=imap.example.com

# E-mail contact
emailAddress=postmaster@example.com

[ cert_type ]
nsCertType = server	 	
EOF

	 	openssl req -new -x509 -nodes -days 365 \
	                -config /tmp/openssl.cnf \
	                -out /assets/certs/server.pem \
	                -keyout /assets/certs/server.key
	 	chmod 0600 /assets/certs/server.key
	    rm -rf /tmp/openssl.cnf


fi

mkdir -p /tmp/state
touch /tmp/state/10-dovecot-init